services:
  behavior-pack:
    build:
      context: ./behavior-pack
      args:
        USER_ID: ${USER_ID} # .envから取得する、事前にupdate_env.shを実行しておくこと
        GROUP_ID: ${GROUP_ID} # USER_IDと同様
    container_name: behaivior-pack
    init: true
    tty: true
    volumes:
      - ./behavior-pack/work:/behavior-pack
  docs:
    build:
      context: ./docs
      args:
        USER_ID: ${USER_ID} # .envから取得する、事前にupdate_env.shを実行しておくこと
        GROUP_ID: ${GROUP_ID} # USER_IDと同様
    container_name: docs
    init: true
    tty: true
    volumes:
      - ./docs/work:/docs
    ports:
      - 5173:5173
