name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/work/src/**'
      - '.github/workflows/publish-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 環境変数を更新
        run: sh update_env.sh

      - name: Docker Composeでビヘイビアパックをビルド & VitePressの環境を起動
        run: docker compose up -d --build

      - name: behaivior-packコンテナのヘルスチェック待機
        run: |
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' behaivior-pack 2>/dev/null || echo "notfound")
            if [ "$STATUS" = "healthy" ]; then
              echo "コンテナは正常です。"
              break
            elif [ "$STATUS" = "notfound" ]; then
              echo "コンテナが見つかりません。待機中..."
            else
              echo "現在のステータス: $STATUS"
            fi
            sleep 5
            if [ $i -eq 30 ]; then
              echo "コンテナが正常になるまでタイムアウトしました。"
              exit 1
            fi
          done

      - name: admin-commands.mcpackをdocs/work/src/publicへ移動
        run: |
          PACK_PATH="behavior-pack/work/dist/admin-commands.mcpack"
          DEST_PATH="docs/work/src/public/admin-commands.mcpack"
          if [ -f "$PACK_PATH" ]; then
            mv "$PACK_PATH" "$DEST_PATH"
          else
            echo "admin-commands.mcpackが見つかりません！" && exit 1
          fi

      - name: docsコンテナのヘルスチェック待機
        run: |
          for i in {1..30}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' docs 2>/dev/null || echo "notfound")
            if [ "$STATUS" = "healthy" ]; then
              echo "コンテナは正常です。"
              break
            elif [ "$STATUS" = "notfound" ]; then
              echo "コンテナが見つかりません。待機中..."
            else
              echo "現在のステータス: $STATUS"
            fi
            sleep 5
            if [ $i -eq 30 ]; then
              echo "コンテナが正常になるまでタイムアウトしました。"
              exit 1
            fi
          done

      - name: VitePressのビルドコマンド実行
        run: docker exec docs npm run docs:build

      - name: GitHub Pagesのセットアップ
        uses: actions/configure-pages@v5

      - name: アーティファクトをアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/work/src/.vitepress/dist

      - name: GitHub Pagesへデプロイ
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Docker Composeのクリーンアップ
        run: docker compose down --rmi local -v
        if: always()
